# Generated by Django 2.0.6 on 2018-06-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20180611_1122'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userorganizationaccess',
            unique_together={('user', 'is_admin')},
        ),
    ]
