# Generated by Django 2.0.6 on 2018-07-20 09:38

from django.db import migrations, models
import uuid

# Simply adds a UUID field to all models, keeps the id fields and all relationships intact


def create_address_uuid(apps, schema_editor):
    mappings = apps.get_model('user_auth', 'Address')
    for mapping in mappings.objects.all():
        mapping.uuid = uuid.uuid4()
        mapping.save()


def create_organization_uuid(apps, schema_editor):
    mappings = apps.get_model('user_auth', 'Organization')
    for mapping in mappings.objects.all():
        mapping.uuid = uuid.uuid4()
        mapping.save()


def create_userorganizationaccess_uuid(apps, schema_editor):
    mappings = apps.get_model('user_auth', 'UserOrganizationAccess')
    for mapping in mappings.objects.all():
        mapping.uuid = uuid.uuid4()
        mapping.save()


def create_userprofile_uuid(apps, schema_editor):
    mappings = apps.get_model('user_auth', 'UserProfile')
    for mapping in mappings.objects.all():
        mapping.uuid = uuid.uuid4()
        mapping.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_auto_20180619_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='uuid',
            field=models.UUIDField(null=True, blank=True)
        ),
        migrations.RunPython(create_address_uuid),
        migrations.AlterField(
            model_name='address',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='uuid',
            field=models.UUIDField(null=True, blank=True)
        ),
        migrations.RunPython(create_organization_uuid),
        migrations.AlterField(
            model_name='organization',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='userorganizationaccess',
            name='uuid',
            field=models.UUIDField(null=True, blank=True)
        ),
        migrations.RunPython(create_userorganizationaccess_uuid),
        migrations.AlterField(
            model_name='userorganizationaccess',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(null=True, blank=True)
        ),
        migrations.RunPython(create_userprofile_uuid),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
