# Generated by Django 2.0.6 on 2018-07-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_add_uuids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='organizations',
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userorganizationaccess',
            name='organization',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userorganizationaccess',
            name='user',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
