# Generated by Django 2.0.6 on 2018-07-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_auto_20180720_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.IntegerField(auto_created=True, null=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.IntegerField(auto_created=True, null=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userorganizationaccess',
            name='id',
            field=models.IntegerField(auto_created=True, null=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.IntegerField(auto_created=True, null=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
