UNKNOWN_ERROR = 'Something went wrong'
ACCESS_DENIED = 'Access Denied'
DATA_INVALID = 'Invalid data passed'
VISIT_NOT_EXIST = 'Visit does not exist'
USER_NOT_EXIST = 'User does not exist'
NO_OR_MULTIPLE_ORGS_FOR_USER = 'User associated with no or multiple organizations'
