# Generated by Django 2.0.6 on 2018-06-11 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soc_date', models.DateField()),
                ('end_date', models.DateField()),
                ('period', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('cpr_code', models.CharField(choices=[('DNR', 'DNR'), ('FULL', 'FULL_CODE'), ('LTD', 'LIMITED_CODE')], default='DNR', max_length=4)),
                ('transportation_level', models.CharField(choices=[('1', 'TAL-1'), ('2', 'TAL-2'), ('3', 'TAL-3')], default='1', max_length=2)),
                ('acuity_type', models.CharField(choices=[('R', 'RED'), ('Y', 'YELLOW'), ('O', 'ORANGE'), ('G', 'GREEN')], default='R', max_length=2)),
                ('classification', models.CharField(max_length=100)),
                ('allergies', models.CharField(max_length=100)),
                ('attending_physician', models.ForeignKey(on_delete=None, related_name='attending_episodes', to='user_auth.UserProfile')),
                ('diagnosis', models.ManyToManyField(to='phi.Diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationPatientsMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=None, to='user_auth.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=10)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=2)),
                ('primary_contact', models.CharField(max_length=15, null=True)),
                ('emergency_contact', models.CharField(max_length=15, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.Address')),
                ('organizations', models.ManyToManyField(through='phi.OrganizationPatientsMapping', to='user_auth.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='UserEpisodeAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(max_length=100)),
                ('episode', models.ForeignKey(on_delete=None, to='phi.Episode')),
                ('organization', models.ForeignKey(on_delete=None, to='user_auth.Organization')),
                ('user', models.ForeignKey(on_delete=None, to='user_auth.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='organizationpatientsmapping',
            name='patient',
            field=models.ForeignKey(on_delete=None, to='phi.Patient'),
        ),
        migrations.AddField(
            model_name='episode',
            name='patient',
            field=models.ForeignKey(on_delete=None, related_name='episodes', to='phi.Patient'),
        ),
        migrations.AddField(
            model_name='episode',
            name='pharmacy',
            field=models.ForeignKey(on_delete=None, to='user_auth.Organization'),
        ),
        migrations.AddField(
            model_name='episode',
            name='primary_physician',
            field=models.ForeignKey(on_delete=None, related_name='primary_episodes', to='user_auth.UserProfile'),
        ),
        migrations.AddField(
            model_name='episode',
            name='soc_clinician',
            field=models.ForeignKey(on_delete=None, related_name='soc_episodes', to='user_auth.UserProfile'),
        ),
    ]
