# Generated by Django 2.0.6 on 2018-06-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='allergies',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='attending_physician',
            field=models.ForeignKey(null=True, on_delete=None, related_name='attending_episodes', to='user_auth.UserProfile'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='classification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='period',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=None, to='user_auth.Organization'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='primary_physician',
            field=models.ForeignKey(null=True, on_delete=None, related_name='primary_episodes', to='user_auth.UserProfile'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='soc_clinician',
            field=models.ForeignKey(null=True, on_delete=None, related_name='soc_episodes', to='user_auth.UserProfile'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='soc_date',
            field=models.DateField(null=True),
        ),
    ]
