# Generated by Django 2.0.6 on 2018-06-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_auto_20180612_1032'),
        ('phi', '0002_auto_20180611_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='acuity_type',
            field=models.CharField(choices=[('R', 'RED'), ('Y', 'YELLOW'), ('O', 'ORANGE'), ('G', 'GREEN')], default='R', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='cpr_code',
            field=models.CharField(choices=[('DNR', 'DNR'), ('FULL', 'FULL_CODE'), ('LTD', 'LIMITED_CODE')], default='DNR', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='transportation_level',
            field=models.CharField(choices=[('1', 'TAL-1'), ('2', 'TAL-2'), ('3', 'TAL-3')], default='1', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='organizationpatientsmapping',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=None, to='user_auth.Organization'),
        ),
        migrations.AlterField(
            model_name='organizationpatientsmapping',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=None, to='phi.Patient'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationpatientsmapping',
            unique_together={('organization', 'patient')},
        ),
    ]
