# Generated by Django 2.0.6 on 2018-06-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phi', '0003_auto_20180613_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationpatientsmapping',
            name='organization',
            field=models.ForeignKey(on_delete=None, to='user_auth.Organization'),
        ),
        migrations.AlterField(
            model_name='organizationpatientsmapping',
            name='patient',
            field=models.ForeignKey(on_delete=None, to='phi.Patient'),
        ),
    ]
