# Generated by Django 2.0.6 on 2018-06-16 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phi', '0004_auto_20180613_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='attending_physician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attending_episodes', to='user_auth.UserProfile'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='phi.Patient'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.Organization'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='primary_physician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_episodes', to='user_auth.UserProfile'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='soc_clinician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soc_episodes', to='user_auth.UserProfile'),
        ),
        migrations.AlterField(
            model_name='organizationpatientsmapping',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.Organization'),
        ),
        migrations.AlterField(
            model_name='organizationpatientsmapping',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phi.Patient'),
        ),
        migrations.AlterField(
            model_name='userepisodeaccess',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phi.Episode'),
        ),
        migrations.AlterField(
            model_name='userepisodeaccess',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.Organization'),
        ),
        migrations.AlterField(
            model_name='userepisodeaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.UserProfile'),
        ),
    ]
