# Generated by Django 2.0.6 on 2018-07-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phi', '0007_auto_20180620_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='emergency_contact',
            new_name='emergency_contact_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
