# Generated by Django 2.0.6 on 2018-07-06 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phi', '0009_physician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='primary_physician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_episodes', to='phi.Physician'),
        ),
    ]
