# Generated by Django 2.0.6 on 2018-07-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phi', '0010_auto_20180706_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_relationship',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
