# Generated by Django 2.0.6 on 2018-07-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phi', '0011_patient_emergency_contact_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='npi',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
