# Generated by Django 2.0.6 on 2018-07-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_auto_20180619_0905'),
        ('phi', '0012_auto_20180712_0821'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userepisodeaccess',
            unique_together={('episode', 'organization', 'user')},
        ),
    ]
