# Generated by Django 2.0.6 on 2018-07-17 09:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_auto_20180619_0905'),
        ('phi', '0013_auto_20180712_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_visit_id', models.CharField(max_length=50, null=True)),
                ('scheduled_at', models.DateTimeField(null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('time_of_completion', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='phi.Episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='user_auth.UserProfile')),
            ],
        ),
    ]
