# Generated by Django 2.0.6 on 2018-07-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phi', '0015_add_uuids'),
        ('user_auth', '0006_add_uuids')
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='organizations',
        ),
        migrations.AlterField(
            model_name='episode',
            name='attending_physician',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='patient',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='episode',
            name='pharmacy',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='primary_physician',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='soc_clinician',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organizationpatientsmapping',
            name='organization',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='organizationpatientsmapping',
            name='patient',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userepisodeaccess',
            name='episode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userepisodeaccess',
            name='organization',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userepisodeaccess',
            name='user',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='visit',
            name='episode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='user',
            field=models.CharField(max_length=10),
        ),
    ]
