# Generated by Django 2.0.6 on 2018-07-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phi', '0019_auto_20180720_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='id',
            field=models.IntegerField(auto_created=True, null=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.IntegerField(auto_created=True, null=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organizationpatientsmapping',
            name='id',
            field=models.IntegerField(auto_created=True, null=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.IntegerField(auto_created=True, null=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='physician',
            name='id',
            field=models.IntegerField(auto_created=True, null=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userepisodeaccess',
            name='id',
            field=models.IntegerField(auto_created=True, null=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
