# Generated by Django 2.0.6 on 2018-07-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phi', '0020_auto_20180723_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='scheduled_at',
        ),
        migrations.AddField(
            model_name='visit',
            name='midnight_epoch',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='planned_start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='is_deleted',
            field=models.NullBooleanField(default=False),
        ),
    ]
