# Generated by Django 2.0.6 on 2018-07-25 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_auto_20180723_1127'),
        ('phi', '0021_auto_20180725_0329'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together={('client_visit_id', 'episode', 'user')},
        ),
    ]
