# Generated by Django 2.0.6 on 2018-07-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phi', '0022_auto_20180725_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='visit',
            name='client_visit_id',
        ),
    ]
