# Generated by Django 2.0.6 on 2018-07-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phi', '0023_auto_20180725_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='midnight_epoch',
        ),
        migrations.AddField(
            model_name='visit',
            name='midnight_epoch',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='visit',
            name='planned_start_time',
        ),
        migrations.AddField(
            model_name='visit',
            name='planned_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
