# Generated by Django 2.0.6 on 2018-07-26 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_auto_20180723_1127'),
        ('phi', '0024_auto_20180725_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='user_auth.Organization'),
        ),
    ]
