# Generated by Django 2.0.6 on 2018-08-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phi', '0025_visit_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='miles_comments',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='odometer_end',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='odometer_start',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='total_miles',
            field=models.FloatField(null=True),
        ),
    ]
