# Generated by Django 2.0.6 on 2018-08-28 07:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


def add_visit_miles_for_existing_visits(apps, _):
    visit_model = apps.get_model('phi', 'Visit')
    visit_miles_model = apps.get_model('phi', 'VisitMiles')
    for visit in visit_model.objects.all():
        visit_miles = visit_miles_model(visit=visit)
        visit_miles.save()


class Migration(migrations.Migration):

    dependencies = [
        ('phi', '0027_auto_20180817_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitMiles',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('updated_by', models.CharField(max_length=50, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('odometer_start', models.FloatField(null=True)),
                ('odometer_end', models.FloatField(null=True)),
                ('total_miles', models.FloatField(null=True)),
                ('miles_comments', models.CharField(max_length=300, null=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit_miles', to='phi.Visit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(add_visit_miles_for_existing_visits),
    ]
