# Generated by Django 2.0.6 on 2018-09-14 22:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_auto_20180817_1008'),
        ('phi', '0029_add_visit_miles_objects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('updated_by', models.CharField(max_length=50, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='user_auth.Address')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
