# Generated by Django 2.0.6 on 2018-09-20 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_auto_20180817_1008'),
        ('phi', '0031_visit_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='physician',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physicians',
                                    to='user_auth.Organization'),
        ),
    ]
