# Generated by Django 2.0.6 on 2018-09-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_auto_20180817_1008'),
        ('phi', '0032_physician_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='npi',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='physician',
            unique_together={('organization', 'npi')},
        ),
    ]
