# Generated by Django 2.0.6 on 2018-10-08 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phi', '0034_auto_20181003_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_episodes', to='user_auth.Organization'),
        ),
        migrations.AlterField(
            model_name='organizationpatientsmapping',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_mapping', to='user_auth.Organization'),
        ),
        migrations.AlterField(
            model_name='organizationpatientsmapping',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_mappings', to='phi.Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='user_auth.Address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='user_auth.Organization'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='user_auth.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userepisodeaccess',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='phi.Episode'),
        ),
        migrations.AlterField(
            model_name='userepisodeaccess',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_episode_accesses', to='user_auth.Organization'),
        ),
        migrations.AlterField(
            model_name='userepisodeaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_accesses', to='user_auth.UserProfile'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='phi.Episode'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='phi.Place'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='user_auth.UserProfile'),
        ),
    ]
