# Generated by Django 2.0.6 on 2018-10-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phi', '0036_auto_20181019_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitmiles',
            old_name='total_miles',
            new_name='computed_miles',
        ),
        migrations.AddField(
            model_name='visitmiles',
            name='extra_miles',
            field=models.FloatField(null=True),
        ),
    ]
